### ISSUE TITLE
Drag&Drop doesn't work

### ISSUE THREAD

**Issue by bi2614** [Pedrokostam/AuroraVisionLauncher#5]
I tried it and it doesn't work, even on admin.

**Comment by MK6554** [comment]
Drag and drop apparently does not work when elevated. Or rather, you can only drag from a source that is elevated as high or higher than the sink (Launcher). Unless the explorer is also running with admin rights, you will not be able to drag&drop to the elevated Launcher.
https://learn.microsoft.com/pl-pl/archive/blogs/patricka/q-why-doesnt-drag-and-drop-work-when-my-application-is-running-elevated-a-mandatory-integrity-control-and-uipi
