### ISSUE TITLE
Autoselect the newest executor

### ISSUE THREAD

**Issue by bi2614** [Pedrokostam/AuroraVisionLauncher#7]
Is it possible that when I click on avexe then program will propose me the newest stable executor?
Right now I get this
![image](https://github.com/user-attachments/assets/6518dd10-3a7d-421b-957b-15bf2c3140fd)

So this one is older, I would like to run it in 5.4.5.73902

Thanks in advance
Bogdan

**Comment by Pedrokostam** [comment]
Fixed in 1.0.0.1
