### ISSUE TITLE
Theme issue

### ISSUE THREAD

**Issue by bi2614** [Pedrokostam/AuroraVisionLauncher#8]
After some time (a few minutes) the dark theme is switching into the light one.

**Comment by Pedrokostam** [comment]
For some reason, the theme may switch to the system theme on its own. You are using the light system theme, so the app also becomes light.

**Comment by Pedrokostam** [comment]
I'm thinking of just deleting the system theme, hammer method style

**Comment by Pedrokostam** [comment]
Turns out I made all themes sync with the system. So anytime the event for updating some system property fired up, the theme was set back to the system's.
Coulda fixed it in one line, actually...
#20
